// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfaj3SjahrqpQjYM5-my6fp2T3apI-RyM',
    appId: '1:66254651905:web:a24c8f9cff9af35ad97600',
    messagingSenderId: '66254651905',
    projectId: 'jhjh-261a5',
    authDomain: 'jhjh-261a5.firebaseapp.com',
    storageBucket: 'jhjh-261a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS-hr7lCt3OwVmOr9GOhjIuiCVnSeizKo',
    appId: '1:66254651905:android:0f5e7da694aca4d3d97600',
    messagingSenderId: '66254651905',
    projectId: 'jhjh-261a5',
    storageBucket: 'jhjh-261a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wLspYeqWhaUiJ7KzNTJHgYZmSNKtx6M',
    appId: '1:66254651905:ios:28c708870ce26d44d97600',
    messagingSenderId: '66254651905',
    projectId: 'jhjh-261a5',
    storageBucket: 'jhjh-261a5.appspot.com',
    iosClientId: '66254651905-acled3pn5k6chvmjuclbh36n0h0jtp9d.apps.googleusercontent.com',
    iosBundleId: 'com.jhjh.jhjh',
  );
}
